services:
    keycloak:
        container_name: keycloak
        depends_on:
            - "kafka"
        image: keycloak-kafka
        ports:
            - "8080:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KAFKA_TOPIC: keycloak-events
            KAFKA_ADMIN_TOPIC: keycloak-admin-events
            KAFKA_CLIENT_ID: keycloak
            KAFKA_BOOTSTRAP_HOST: kafka:9092
        command: start-dev
        healthcheck:
            test: [ "CMD", "bash", "-c", "echo -n > /dev/null && /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin --client admin-cli && /opt/keycloak/bin/kcadm.sh get realms --fields id --server http://localhost:8080/auth --realm master --user admin --password admin --client admin-cli" ]
            interval: 10s
            timeout: 5s
            retries: 3

    zookeeper:
        container_name: zookeeper
        restart: always
        image: bitnami/zookeeper:latest
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        healthcheck:
            test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok" ]
            interval: 10s
            timeout: 5s
            retries: 3

    kafka:
        container_name: kafka
        depends_on:
            - "zookeeper"
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
            - "9094:9094"
        environment:
            KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
            KAFKA_CFG_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: "yes"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        healthcheck:
            test: [ "CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list" ]
            start_period: 15s
            interval: 10s
    init-kafka:
        image: bitnami/kafka:latest
        command: [ "/bin/bash", "-c", "/create_topic.sh"]
        container_name: kafka-init
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_TOPIC: keycloak-events
            KAFKA_ADMIN_TOPIC: keycloak-admin-events
            KAFKA_CLIENT_ID: keycloak
            KAFKA_BOOT_SERVER_NAME: kafka
            KAFKA_BOOT_SERVER_PORT: 9092
        depends_on:
            kafka:
                condition: service_started
        volumes:
            - type: bind
              source: ./scripts/create_topic.sh
              target: /create_topic.sh
        init: true
